source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 3.0'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'Kingfisher', '~> 1.8'
pod "PKHUD"
pod 'ReachabilitySwift', git: 'https://github.com/ashleymills/Reachability.swift'
